### ISSUE TITLE
Dotfiles are not moved/copied into public/

### ISSUE THREAD

**Issue by edmorley** [cloudfoundry-incubator/staticfile-buildpack#19]
As part of the compile, files in $root_dir are moved into public/.

There are a few issues:
1) |mv| doesn't include dotfiles/dot-directories, so we end up with some files present in public/ and some left behind. I believe we should move/copy _all_ files, since (a) that seems more predictable, and (b) people can already exclude files using their manifest (and in fact the default ignore-files excludes dotfiles anyway).
2) The message says "Copying", but we use |mv|. We should change one or the other.

**Comment by jchesterpivotal** [comment]
Worth comparing with the behaviour of PHP buildpack, which has a similar "move and filter" strategy. In that case it introduces a lot of complexity because other parts of the buildpack have to be aware of the relocation.

**Comment by edmorley** [comment]
My use case is:

```yaml
name: test
instances: 1
mem: 64M
framework:
  type: buildpack
env:
  BUILDPACK_URL: git://github.com/cloudfoundry-incubator/staticfile-buildpack.git
  FORCE_HTTPS: true
hooks:
  pre-staging:
  - git clone --depth 1 https://github.com/foo/bar.git src
cron: 
  - "* * * * * cd $HOME/public/src && git pull"
```
With a Staticfile containing:
```yaml
root: src
```

...to have a simple static files site auto-update from Github.

Unfortunately at the moment, the .git directory isn't copied to public/, so the |git pull| of the cron fails. In addition, since the working directory of the repo ($HOME/src) was |mv|ed, I need to reset the working directory, git pull, then rsync the files to $HOME/public/src - which is all a bit of a dance just to get a simple site live. (And yeah I know for many people they wouldn't want the .git directory in public, but it really doesn't matter for this use case).
